import { test, expect } from '@playwright/test';
import path from 'node:path';
import { existsSync } from 'node:fs';

test('inventory uses the supplied full DMC catalog and RGB colors', async ({ page, request }) => {
  const catalog = await (await request.get('/api/catalog')).json();
  expect(catalog).toHaveLength(454);
  expect(catalog.find((t: { code: string }) => t.code === '309').displayColor).toBe('#564A4A');
  await page.goto('/');
  await page.getByRole('button', { name: 'Thread collection', exact: true }).click();
  await page.getByRole('textbox', { name: 'Search thread catalog' }).fill('3713');
  await expect(page.locator('.thread-table-row')).toHaveCount(1);
  await expect(page.locator('.thread-table-row')).toContainText('Salmon Very Light');
  await expect(page.locator('.floss-swatch')).toHaveCSS('background-color', 'rgb(255, 226, 226)');
  await page.getByRole('textbox', { name: 'Search thread catalog' }).fill('White');
  await expect(page.locator('.thread-table')).toContainText('DMC White');
});

test('stitching, undo, substitutions, inventory, and persisted reload', async ({ page, request }) => {
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
  await page.goto('/');
  await expect(page.getByRole('heading', { name: 'My projects' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'A new beginning' })).toBeVisible();
  await page.screenshot({ path: '../artifacts/library-empty.png', fullPage: true });
  await page.getByRole('button', { name: 'Import a pattern', exact: true }).click();
  await page.getByRole('button', { name: 'Explore with the little garden sampler' }).click();
  await expect(page.getByRole('heading', { name: 'The little garden', exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Mark matching complete', exact: true })).toBeEnabled();
  await page.screenshot({ path: '../artifacts/workspace.png', fullPage: true });
  const projectList = await (await request.get('/api/projects')).json();
  const id = projectList.find((p: { name: string }) => p.name === 'The little garden').id;
  await page.getByLabel('Apply completion to').selectOption('pattern');
  await page.getByRole('button', { name: 'Mark matching complete', exact: true }).click();
  await expect(page.locator('.workspace-progress')).toContainText('100.0');
  await expect(page.getByRole('button', { name: 'Undo', exact: true })).toBeEnabled();
  await page.getByRole('button', { name: 'Undo', exact: true }).click();
  await expect(page.locator('.workspace-progress')).toContainText('0.0');
  await expect(page.getByRole('button', { name: 'Redo', exact: true })).toBeEnabled();
  await page.getByRole('button', { name: 'Redo', exact: true }).click();
  await expect(page.locator('.workspace-progress')).toContainText('100.0');
  await expect(page.getByRole('button', { name: 'Undo', exact: true })).toBeEnabled();
  await page.getByRole('button', { name: 'Undo', exact: true }).click();
  await expect(page.locator('.save-status')).toContainText('Saved');
  // Select a real definition, then bulk-mark only that color.
  await page.locator('.key-choice').first().click();
  await page.getByRole('button', { name: 'Mark matching complete', exact: true }).click();
  await expect(page.locator('.save-status')).toContainText('Saved');
  const saved = await (await request.get(`/api/projects/${id}`)).json();
  expect(saved.completed.length).toBeGreaterThan(0); expect(saved.completed.length).toBeLessThan(saved.data.stitches.length);
  await page.getByRole('button', { name: 'Threads', exact: true }).click();
  await page.getByLabel('Replacement for DMC 500', { exact: true }).selectOption('310');
  await expect(page.locator('.save-status')).toContainText('Saved');
  expect((await (await request.get(`/api/projects/${id}`)).json()).substitutions['500']).toBe('310');
  await page.getByRole('button', { name: 'Thread collection', exact: true }).click();
  await page.getByRole('textbox', { name: 'Search thread catalog' }).fill('310');
  await page.getByRole('button', { name: 'Add to collection', exact: true }).click();
  await page.getByLabel('Whole bobbins').fill('3'); await page.getByLabel('Where is it stored?').fill('Box 1 / Row 3');
  await page.getByRole('button', { name: 'Save to collection', exact: true }).click();
  await expect(page.locator('.thread-table-row')).toContainText('Box 1 / Row 3');
  await page.evaluate(() => { localStorage.clear(); sessionStorage.clear(); });
  await page.reload();
  await page.getByRole('button', { name: 'Open The little garden', exact: true }).first().click();
  await expect(page.locator('.workspace-progress')).toContainText(`${(saved.completed.length / saved.data.stitches.length * 100).toFixed(1)}`);
  expect(errors).toEqual([]);
});

test('structured PDF import requires audit and can be corrected', async ({ page, request }) => {
  await page.goto('/'); await page.getByRole('button', { name: 'Import a pattern', exact: true }).click();
  await page.locator('input[type=file]').setInputFiles(path.resolve('../artifacts/structured-sampler.pdf'));
  await expect(page.getByRole('heading', { name: 'structured-sampler', exact: true })).toBeVisible();
  await expect(page.getByText('Does this look like your pattern?')).toBeVisible();
  await expect(page.locator('.workspace-title')).toContainText('10 × 20');
  await expect(page.locator('.key-choice')).toContainText('DMC 310');
  await page.screenshot({ path: '../artifacts/import-audit.png', fullPage: true });
  await page.getByRole('button', { name: 'Edit symbol X', exact: true }).click();
  await page.getByLabel('Symbol', { exact: true }).fill('+');
  await page.getByRole('button', { name: 'Save definition' }).click();
  await expect(page.getByRole('button', { name: 'Edit symbol +', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Looks good, start stitching' }).click();
  await expect(page.getByText('Does this look like your pattern?')).not.toBeVisible();
  await page.getByLabel('Apply completion to').selectOption('pattern');
  await page.getByRole('button', { name: 'Mark matching complete', exact: true }).click();
  await expect(page.locator('.workspace-progress')).toContainText('100.0');
  await expect(page.locator('.save-status')).toContainText('Saved');
  const p = (await (await request.get('/api/projects')).json()).find((p: { name: string }) => p.name === 'structured-sampler');
  expect(p.completed).toBe(200);
});

test('working area, painting, erasing, edit undo, and save failure', async ({ page, request }) => {
  const response = await request.post('/api/projects/sample'); const p = await response.json();
  await request.post(`/api/projects/${p.id}/commands`, { data: { revision: 0, kind: 'rename', name: 'Canvas test' } });
  await page.goto('/'); await page.getByRole('button', { name: 'Open Canvas test', exact: true }).click();
  await page.getByRole('button', { name: 'Working area', exact: true }).click();
  const canvas = page.locator('.canvas-panel canvas'); const bounds = (await canvas.boundingBox())!;
  // Fit transform is deterministic: 90px margin, capped at 28px/cell.
  const cell = Math.min(28, (bounds.width - 90) / 100, (bounds.height - 90) / 100);
  const ox = (bounds.width - 100 * cell) / 2, oy = (bounds.height - 100 * cell) / 2;
  const point = (x: number, y: number) => ({ x: bounds.x + ox + (x + .5) * cell, y: bounds.y + oy + (y + .5) * cell });
  const start = point(15, 10), end = point(45, 40);
  await page.mouse.move(start.x, start.y); await page.mouse.down(); await page.mouse.move(end.x, end.y, { steps: 10 }); await page.mouse.up();
  await expect(page.locator('.area-card')).toContainText('Columns 16–46');
  await expect(page.locator('.save-status')).toContainText('Saved');
  await page.getByRole('button', { name: 'Mark matching complete', exact: true }).click();
  await expect(page.locator('.save-status')).toContainText('Saved');
  let saved = await (await request.get(`/api/projects/${p.id}`)).json();
  expect(saved.completed.length).toBeGreaterThan(0);
  const completed = new Set(saved.completed); expect(saved.data.stitches.filter((s: { id: string; x: number; y: number }) => completed.has(s.id)).every((s: { x: number; y: number }) => s.x >= 15 && s.x <= 45 && s.y >= 10 && s.y <= 40)).toBe(true);
  await page.getByRole('button', { name: 'Undo', exact: true }).click(); await expect(page.locator('.save-status')).toContainText('Saved');
  const stitch = saved.data.stitches.find((s: { x: number; y: number }) => s.x >= 15 && s.x <= 45 && s.y >= 10 && s.y <= 40);
  const spot = point(stitch.x, stitch.y);
  await page.getByRole('button', { name: 'Paint complete', exact: true }).click(); await page.mouse.click(spot.x, spot.y);
  await expect(page.locator('.save-status')).toContainText('Saved');
  saved = await (await request.get(`/api/projects/${p.id}`)).json(); expect(saved.completed).toContain(stitch.id);
  await page.getByRole('button', { name: 'Paint incomplete', exact: true }).click(); await page.mouse.click(spot.x, spot.y);
  await expect(page.locator('.save-status')).toContainText('Saved');
  saved = await (await request.get(`/api/projects/${p.id}`)).json(); expect(saved.completed).not.toContain(stitch.id);
  await page.getByRole('button', { name: 'Edit stitches', exact: true }).click(); await page.mouse.click(spot.x, spot.y);
  await page.getByRole('button', { name: 'Remove stitch', exact: true }).click(); await expect(page.locator('.save-status')).toContainText('Saved');
  saved = await (await request.get(`/api/projects/${p.id}`)).json(); expect(saved.data.stitches.some((s: { id: string }) => s.id === stitch.id)).toBe(false);
  await page.getByRole('button', { name: 'Undo', exact: true }).click(); await expect(page.locator('.save-status')).toContainText('Saved');
  await page.route('**/api/projects/*/commands', route => route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: 'Server unavailable.' }) }));
  await page.getByRole('button', { name: 'Mark matching complete', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('last confirmed save');
  await expect(page.locator('.workspace-progress')).toContainText('0.0');
});

test('backup download and large-pattern viewport stays bounded', async ({ page, request }) => {
  await page.goto('/'); await page.getByRole('button', { name: 'Backups & care', exact: true }).click();
  await page.getByRole('button', { name: 'Back up now', exact: true }).click();
  await expect(page.locator('.backup-row').first()).toBeVisible();
  const href = await page.getByRole('link', { name: 'Download' }).first().getAttribute('href');
  expect((await request.get(href!)).status()).toBe(200);
  const begin = Date.now(); const p = await (await request.post('/api/projects/sample?size=1000')).json();
  await request.post(`/api/projects/${p.id}/commands`, { data: { revision: 0, kind: 'rename', name: 'Large benchmark' } });
  await page.goto('/'); await page.getByRole('button', { name: 'Open Large benchmark', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Paint complete', exact: true })).toBeEnabled();
  expect(p.data.stitches.length).toBeGreaterThan(100000);
  expect(await page.locator('canvas').count()).toBe(1);
  expect(await page.locator('*').count()).toBeLessThan(600);
  for (let i = 0; i < 10; i++) await page.getByRole('button', { name: 'Zoom in', exact: true }).click();
  await page.locator('.key-choice').first().click(); await page.getByLabel('Isolate matching stitches').check();
  await page.getByRole('button', { name: 'Pan', exact: true }).click();
  const canvas = (await page.locator('canvas').boundingBox())!;
  await page.mouse.move(canvas.x + 150, canvas.y + 150); await page.mouse.down(); await page.mouse.move(canvas.x + 210, canvas.y + 200, { steps: 10 }); await page.mouse.up();
  await page.locator('.key-choice').last().click();
  await expect(page.getByRole('button', { name: 'Mark matching complete', exact: true })).toBeEnabled();
  const startSave = Date.now();
  await page.getByRole('button', { name: 'Mark matching complete', exact: true }).click();
  await expect(page.locator('.save-status')).toContainText('Saved');
  const saved = await (await request.get(`/api/projects/${p.id}`)).json();
  expect(saved.completed.length).toBeGreaterThan(100);
  console.log(`Large viewport completion: ${saved.completed.length} stitches saved in ${Date.now() - startSave}ms`);
  await page.getByRole('button', { name: 'Undo', exact: true }).click();
  await expect(page.locator('.save-status')).toContainText('Saved');
  // Paint a stroke across the central star after fitting and zooming at the center.
  await page.getByRole('button', { name: 'Fit pattern', exact: true }).click();
  for (let i = 0; i < 12; i++) await page.getByRole('button', { name: 'Zoom in', exact: true }).click();
  await page.getByRole('button', { name: 'Paint complete', exact: true }).click();
  const paintStart = Date.now();
  await page.mouse.move(canvas.x + canvas.width / 2 - 30, canvas.y + canvas.height / 2); await page.mouse.down(); await page.mouse.move(canvas.x + canvas.width / 2 + 30, canvas.y + canvas.height / 2, { steps: 8 }); await page.mouse.up();
  await expect(page.locator('.save-status')).toContainText('Saved');
  expect((await (await request.get(`/api/projects/${p.id}`)).json()).completed.length).toBeGreaterThan(0);
  console.log(`Large-pattern paint stroke saved in ${Date.now() - paintStart}ms`);
  await page.screenshot({ path: '../artifacts/large-pattern.png', fullPage: true });
  console.log(`Large pattern ${p.data.stitches.length} stitches: create, load, zoom, filter, and pan in ${Date.now() - begin}ms`);
});

test('supplied symbol-font PDF imports with verified counts and real symbol shapes', async ({ page, request }) => {
  const source = path.resolve('../docs/sample-patterns/Spider-ManBWChart.pdf');
  test.skip(!existsSync(source), 'User-provided PDF is absent; synthetic importer regressions still run.');
  const errors: string[] = [];
  page.on('pageerror', e => errors.push(e.message));
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
  await page.goto('/'); await page.getByRole('button', { name: 'Import a pattern', exact: true }).click();
  await page.locator('input[type=file]').setInputFiles(source);
  await expect(page.getByRole('heading', { name: 'Spider-ManBWChart', exact: true })).toBeVisible();
  await expect(page.locator('.workspace-title')).toContainText('200 × 300');
  await expect(page.locator('.workspace-title')).toContainText('78 colors');
  await expect(page.locator('.workspace-progress')).toContainText('60,000');
  await expect(page.locator('.audit-notes')).toContainText('5,208');
  await expect(page.locator('.audit-notes')).toContainText('78 threads');
  await expect(page.locator('.key-choice .source-symbol')).toHaveCount(78);
  const bounds = await page.locator('.key-choice .source-symbol path').evaluateAll(paths => paths.map(p => { const b = (p as SVGGraphicsElement).getBBox(); return { width: b.width, height: b.height }; }));
  expect(bounds.every(b => b.width > 0 && b.height > 0)).toBe(true);
  await page.screenshot({ path: '../artifacts/supplied-pdf-audit.png', fullPage: true });
  await page.getByRole('button', { name: 'Looks good, start stitching' }).click();
  await expect(page.getByText('Does this look like your pattern?')).not.toBeVisible();
  await page.getByLabel('Apply completion to').selectOption('pattern');
  await page.locator('.key-choice').filter({ hasText: 'DMC 310' }).click();
  await expect(page.locator('.scope-summary')).toContainText('5,119');
  await page.getByRole('button', { name: 'Mark matching complete', exact: true }).click();
  await expect(page.locator('.save-status')).toContainText('Saved');
  const projects = await (await request.get('/api/projects')).json();
  expect(projects.find((p: { name: string }) => p.name === 'Spider-ManBWChart').completed).toBe(5119);
  await page.getByRole('button', { name: 'Clear selection & filters' }).click();
  for (let i = 0; i < 9; i++) await page.getByRole('button', { name: 'Zoom in', exact: true }).click();
  await page.screenshot({ path: '../artifacts/supplied-pdf-symbols.png', fullPage: true });
  expect(errors).toEqual([]);
});
