import { test, expect } from './fixtures';

test('focus keeps the current place, filters, marking, and save errors accessible', async ({ page, request }) => {
  const project = await (await request.post('/api/projects/sample')).json();
  await request.post(`/api/projects/${project.id}/commands`, { data: { revision: 0, kind: 'rename', name: 'Focus test' } });
  await page.goto('/');
  await page.getByRole('button', { name: 'Open Focus test', exact: true }).click();
  await page.locator('.key-choice').first().click();
  await page.getByLabel('Isolate matching stitches').check();
  for (let i = 0; i < 5; i++) await page.getByRole('button', { name: 'Zoom in', exact: true }).click();
  const canvas = page.locator('.canvas-panel canvas');
  const originalBounds = (await canvas.boundingBox())!;
  await page.getByRole('button', { name: 'Pan', exact: true }).click();
  await page.mouse.move(originalBounds.x + originalBounds.width / 2, originalBounds.y + originalBounds.height / 2);
  await page.mouse.down(); await page.mouse.move(originalBounds.x + originalBounds.width / 2 + 23, originalBounds.y + originalBounds.height / 2 + 17); await page.mouse.up();
  const centerCoordinate = async () => {
    const bounds = (await canvas.boundingBox())!;
    await page.mouse.move(bounds.x + bounds.width / 2, bounds.y + bounds.height / 2);
    return page.locator('.canvas-coordinate').innerText();
  };
  const coordinate = await centerCoordinate();
  const zoom = await page.locator('.zoom-controls>span').innerText();
  await page.getByRole('button', { name: 'Focus pattern', exact: true }).click();
  await expect(page.locator('.sidebar')).toBeHidden();
  await expect(page.locator('.topbar')).toBeHidden();
  await expect(page.locator('.pattern-key')).toBeHidden();
  await expect(page.locator('.tools-panel')).toBeHidden();
  await expect(page.locator('.save-status')).toBeVisible();
  await expect(page.locator('.focus-context')).toContainText('Isolated');
  await page.locator('.title-button').click();
  await expect(page.getByRole('dialog')).toBeVisible();
  await page.keyboard.press('Escape');
  await expect(page.getByRole('dialog')).toBeHidden();
  await expect(page.getByRole('button', { name: 'Exit focus', exact: true })).toBeVisible();
  await expect(page.locator('.zoom-controls>span')).toHaveText(zoom);
  await expect.poll(centerCoordinate).toBe(coordinate);
  expect((await canvas.boundingBox())!.width).toBeGreaterThan(originalBounds.width + 400);
  await page.keyboard.press('Escape');
  await expect(page.getByRole('button', { name: 'Focus pattern', exact: true })).toBeFocused();
  await expect(page.locator('.key-choice').first()).toHaveAttribute('aria-pressed', 'true');
  await expect(page.getByLabel('Isolate matching stitches')).toBeChecked();
  await expect.poll(centerCoordinate).toBe(coordinate);
  await expect(page.locator('.zoom-controls>span')).toHaveText(zoom);

  await page.getByRole('button', { name: 'Clear selection & filters', exact: true }).click();
  await page.getByRole('button', { name: 'Focus pattern', exact: true }).click();
  await page.getByRole('button', { name: 'Fit pattern', exact: true }).click();
  await page.getByRole('button', { name: 'Paint complete', exact: true }).click();
  const bounds = (await canvas.boundingBox())!;
  const cell = Math.min(28, (bounds.width - 90) / project.data.width, (bounds.height - 90) / project.data.height);
  const stitch = project.data.stitches[0];
  const x = bounds.x + (bounds.width - project.data.width * cell) / 2 + (stitch.x + .5) * cell;
  const y = bounds.y + (bounds.height - project.data.height * cell) / 2 + (stitch.y + .5) * cell;
  await page.mouse.click(x, y);
  await expect.poll(async () => (await (await request.get(`/api/projects/${project.id}`)).json()).completed).toContain(stitch.id);
  await expect(page.locator('.save-status')).toContainText('Saved');
  await page.getByRole('button', { name: 'Undo', exact: true }).click();
  await expect.poll(async () => (await (await request.get(`/api/projects/${project.id}`)).json()).completed).toHaveLength(0);
  await expect(page.locator('.save-status')).toContainText('Saved');
  await page.screenshot({ path: '../artifacts/focused-pattern.png', fullPage: true });

  await page.route('**/api/projects/*/progress', route => route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: 'Server unavailable.' }) }));
  await page.mouse.click(x, y);
  await expect(page.getByRole('alert')).toContainText('not yet confirmed');
  await expect(page.getByRole('button', { name: 'Retry saving' })).toBeInViewport();
  await expect(page.getByRole('button', { name: 'Exit focus', exact: true })).toBeInViewport();
  await page.getByRole('button', { name: 'Exit focus', exact: true }).click();
  await expect(page.locator('.sidebar')).toBeVisible();
});

test('focused pattern fits a narrow window and exits during a pending save', async ({ page, request }) => {
  const project = await (await request.post('/api/projects/sample')).json();
  await request.post(`/api/projects/${project.id}/commands`, { data: { revision: 0, kind: 'rename', name: 'Narrow focus test' } });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('/');
  await page.getByRole('button', { name: 'Open Narrow focus test', exact: true }).click();
  await page.getByRole('button', { name: 'Focus pattern', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Exit focus', exact: true })).toBeInViewport();
  await expect(page.locator('.save-status')).toBeInViewport();
  const bounds = (await page.locator('.canvas-panel canvas').boundingBox())!;
  expect(bounds.width).toBeGreaterThan(350);
  expect(bounds.height).toBeGreaterThan(400);
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);
  await page.screenshot({ path: '../artifacts/focused-pattern-narrow.png', fullPage: true });
  await page.getByRole('button', { name: 'Change thread or filters', exact: true }).click();
  await expect(page.locator('.pattern-key')).toBeVisible();
  // Hold a real save response so Escape must remain available while busy.
  let release!: () => void;
  const gate = new Promise<void>(resolve => { release = resolve; });
  await page.route('**/api/projects/*/progress', async route => { await gate; await route.continue(); });
  await page.getByLabel('Apply completion to').selectOption('pattern');
  await page.getByRole('button', { name: 'Mark matching complete', exact: true }).click();
  await page.getByRole('button', { name: 'Focus pattern', exact: true }).click();
  await expect(page.locator('.save-status')).toContainText('Saving');
  await page.keyboard.press('Escape');
  await expect(page.getByRole('button', { name: 'Focus pattern', exact: true })).toBeFocused();
  release();
  await expect(page.getByRole('button', { name: 'Undo', exact: true })).toBeEnabled();
  await page.getByRole('button', { name: 'Back to projects' }).click();
  await expect(page.locator('.sidebar')).toBeVisible();
  await expect(page.locator('.topbar')).toBeVisible();
});
