import { useCallback, useEffect, useRef, useState } from 'react';
import { api } from './types';
import { ReleaseMarkdown } from './BetaExperience';
import { FeedbackDetails, type FeedbackDetail } from './FeedbackDetails';

interface Ticket { id: string; userId: string; category: string; status: string; createdAt: string; completedAt?: string; hasAttachments: boolean }
type Detail = FeedbackDetail;
interface Release { id: string; version: string; title: string; bodyMarkdown: string; publishedAt?: string }
interface Announcement { id: string; title: string; active: boolean; publishedAt?: string }
export function BetaAdmin() {
  const reportTrigger = useRef<HTMLButtonElement | null>(null), statusFilter = useRef<HTMLSelectElement | null>(null);
  const restoreReportFocus = useCallback(() => {
    if (reportTrigger.current?.isConnected) reportTrigger.current.focus();
    else statusFilter.current?.focus();
  }, []);
  const [tickets, setTickets] = useState<Ticket[] | null>(null), [detail, setDetail] = useState<Detail | null>(null), [status, setStatus] = useState('Unread'), [archived, setArchived] = useState(false), [page, setPage] = useState(0);
  const [error, setError] = useState(''), [busy, setBusy] = useState(false), [notice, setNotice] = useState('');
  const [releases, setReleases] = useState<Release[]>([]), [announcements, setAnnouncements] = useState<Announcement[]>([]);
  const [release, setRelease] = useState({ version: '', title: '', bodyMarkdown: '', releaseDate: new Date().toISOString().slice(0, 10), publish: false });
  const [announcement, setAnnouncement] = useState({ title: '', message: '', linkText: '', linkUrl: '', startsAt: '', endsAt: '', active: true, dismissible: true, publish: false });
  const [dirty, setDirty] = useState(false);
  const load = async () => {
    const [f, r, a] = await Promise.all([api<Ticket[]>(`/admin/beta/feedback?status=${status}&includeArchived=${archived}&page=${page}`), api<Release[]>('/admin/beta/releases'), api<Announcement[]>('/admin/beta/announcements')]);
    setTickets(f); setReleases(r); setAnnouncements(a);
  };
  useEffect(() => { void load().catch(e => setError(e.message)); }, [status, archived, page]);
  useEffect(() => { const prevent = (e: BeforeUnloadEvent) => { if (dirty) { e.preventDefault(); e.returnValue = ''; } }; window.addEventListener('beforeunload', prevent); return () => window.removeEventListener('beforeunload', prevent); }, [dirty]);
  async function run(action: () => Promise<void>) { if (busy) return; setBusy(true); setError(''); try { await action(); await load(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  return <main className="beta-page beta-admin"><a href="/">Back to projects</a><h1>Beta administration</h1>{error && <p role="alert">{error}<button onClick={() => run(async () => {})}>Retry</button></p>}{notice && <p role="status">{notice}</p>}
    <h2>Feedback</h2><label>Status <select ref={statusFilter} aria-label="Status" value={status} onChange={e => { setStatus(e.target.value); setPage(0); }}>{['Unread', 'Read', 'Completed', 'Archived'].map(s => <option key={s}>{s}</option>)}</select></label>{status === 'Completed' && <label><input type="checkbox" checked={archived} onChange={e => { setArchived(e.target.checked); setPage(0); }}/> Include archived completed reports</label>}
    {tickets === null ? <p>Loading feedback…</p> : tickets.length === 0 ? <p>No feedback matches this view. Choose another status or check back later.</p> : <table><thead><tr><th>Category</th><th>Account</th><th>Received</th><th>Status</th><th>Details</th></tr></thead><tbody>{tickets.map(t => <tr key={t.id}><td>{t.category}</td><td>{t.userId}</td><td>{new Date(t.createdAt).toLocaleString()}</td><td>{t.status}{t.completedAt && ' · addressed'}</td><td><button disabled={busy} onClick={event => { reportTrigger.current = event.currentTarget; void run(async () => setDetail(await api<Detail>(`/admin/beta/feedback/${t.id}`))); }}>Open report {t.id.slice(0, 8)}</button>{t.hasAttachments && <span> · attachment</span>}</td></tr>)}</tbody></table>}
    <div className="beta-actions"><button disabled={busy || page === 0} onClick={() => setPage(page - 1)}>Previous page</button><button disabled={busy || tickets?.length !== 50} onClick={() => setPage(page + 1)}>Next page</button></div>
    {detail && <FeedbackDetails detail={detail} busy={busy} error={error} restoreFocus={restoreReportFocus} close={() => !busy && setDetail(null)} changeStatus={nextStatus => { void run(async () => {
      await api(`/admin/beta/feedback/${detail.report.id}/status`, 'POST', { status: nextStatus });
      setDetail(await api<Detail>(`/admin/beta/feedback/${detail.report.id}`));
    }); }} />}
    <h2>Announcements</h2><ul>{announcements.map(a => <li key={a.id}>{a.title} · {a.publishedAt ? 'Published' : 'Draft'} · {a.active ? 'Active' : 'Inactive'} <button disabled={busy} onClick={() => run(async () => { await api(`/admin/beta/announcements/${a.id}/state`, 'POST', { active: !a.active, publish: false }); })}>{a.active ? 'Deactivate' : 'Activate'}</button>{!a.publishedAt && <button disabled={busy} onClick={() => run(async () => { await api(`/admin/beta/announcements/${a.id}/state`, 'POST', { active: a.active, publish: true }); })}>Publish announcement</button>}</li>)}</ul>
    <details><summary>Create announcement</summary><form onChange={() => setDirty(true)} onSubmit={e => { e.preventDefault(); void run(async () => { await api('/admin/beta/announcements', 'POST', { ...announcement, startsAt: announcement.startsAt ? new Date(announcement.startsAt).toISOString() : null, endsAt: announcement.endsAt ? new Date(announcement.endsAt).toISOString() : null }); setAnnouncement({ title: '', message: '', linkText: '', linkUrl: '', startsAt: '', endsAt: '', active: true, dismissible: true, publish: false }); setDirty(false); setNotice('Announcement saved.'); }); }}><fieldset disabled={busy}>{(['title', 'message', 'linkText', 'linkUrl', 'startsAt', 'endsAt'] as const).map(key => <label key={key}>{({ title: 'Announcement title', message: 'Short message', linkText: 'Link text', linkUrl: 'HTTPS URL or /whats-new', startsAt: 'Start time (local)', endsAt: 'End time (local)' })[key]}<input type={key.endsWith('At') ? 'datetime-local' : 'text'} required={key === 'title' || key === 'message'} maxLength={key === 'message' ? 1000 : key === 'title' ? 120 : undefined} value={announcement[key]} onChange={e => setAnnouncement({ ...announcement, [key]: e.target.value })}/></label>)}{(['active', 'dismissible', 'publish'] as const).map(key => <label key={key}><input type="checkbox" checked={announcement[key]} onChange={e => setAnnouncement({ ...announcement, [key]: e.target.checked })}/>{key === 'publish' ? 'Publish immediately' : key}</label>)}<button className="primary">Save announcement</button></fieldset></form></details>
    <h2>Release notes</h2><ul>{releases.map(r => <li key={r.id}>{r.version} · {r.title} · {r.publishedAt ? 'Published' : 'Draft'}{!r.publishedAt && <button disabled={busy} onClick={() => run(async () => { await api(`/admin/beta/releases/${r.id}/publish`, 'POST'); })}>Publish release</button>}</li>)}</ul>
    <details><summary>Create release entry</summary><form onChange={() => setDirty(true)} onSubmit={e => { e.preventDefault(); void run(async () => { await api('/admin/beta/releases', 'POST', release); setRelease({ version: '', title: '', bodyMarkdown: '', releaseDate: new Date().toISOString().slice(0, 10), publish: false }); setDirty(false); setNotice('Release entry saved.'); }); }}><fieldset disabled={busy}><label>Version<input required maxLength={80} value={release.version} onChange={e => setRelease({ ...release, version: e.target.value })}/></label><label>Release date<input required type="date" value={release.releaseDate} onChange={e => setRelease({ ...release, releaseDate: e.target.value })}/></label><label>Release title<input required maxLength={160} value={release.title} onChange={e => setRelease({ ...release, title: e.target.value })}/></label><label>Release notes<textarea required maxLength={20000} rows={8} value={release.bodyMarkdown} onChange={e => setRelease({ ...release, bodyMarkdown: e.target.value })}/></label><p>Supported Markdown: headings, paragraphs, and bullet lists. HTML and other markup display as text.</p><ReleaseMarkdown text={release.bodyMarkdown}/><label><input type="checkbox" checked={release.publish} onChange={e => setRelease({ ...release, publish: e.target.checked })}/>Publish immediately</label><button className="primary">Save release</button></fieldset></form></details>
  </main>;
}
